FROM openjdk:8-jdk-alpine

WORKDIR /testspace
COPY search-docker-test/target/search-docker-test-0.0.1-runnable.jar search-docker-test-0.0.1.jar
COPY search-docker-test/search_title_testsuite.xml .

RUN apk update && \
    apk add firefox-esr

RUN wget -q "https://repo1.maven.org/maven2/org/testng/testng/6.7/testng-6.7.jar" -O /testspace/testng-6.7.jar

CMD ["java", "-cp", "/testspace/*", "org.testng.TestNG", "/testspace/search_title_testsuite.xml"]
